<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LKSRIWL-DYFG2X2" ignored="0" name="Daraz_Suite" tests="2" failures="1" timestamp="2021-11-10T19:29:16 IST" time="112.093" errors="0">
  <testcase name="verifyFromTheSameStroeItemCount" time="45.373" classname="com.qe.daraz.TestObjects.DarazTest">
    <failure type="java.lang.AssertionError" message="same store item count not matched expected [4] but found [0]">
      <![CDATA[java.lang.AssertionError: same store item count not matched expected [4] but found [0]
at com.qe.daraz.TestObjects.DarazTest.verifyFromTheSameStroeItemCount(DarazTest.java:53)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyFromTheSameStroeItemCount -->
  <testcase name="verifyFromTheSameStroeItemPriceRange" time="30.301" classname="com.qe.daraz.TestObjects.DarazTest"/>
</testsuite> <!-- Daraz_Suite -->
