<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LKSRIWL-DYFG2X2" ignored="0" name="TimedAssignment_AAndP_RegressionSuite" tests="2" failures="1" timestamp="2021-11-10T19:22:34 IST" time="119.779" errors="0">
  <testcase name="verifyFromTheSameStroeItemCount" time="38.276" classname="com.qe.daraz.TestObjects.DarazTest">
    <failure type="java.lang.AssertionError" message="same store item count not matched expected [4] but found [0]">
      <![CDATA[java.lang.AssertionError: same store item count not matched expected [4] but found [0]
at com.qe.daraz.TestObjects.DarazTest.verifyFromTheSameStroeItemCount(DarazTest.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyFromTheSameStroeItemCount -->
  <testcase name="verifyFromTheSameStroeItemPriceRange" time="36.534" classname="com.qe.daraz.TestObjects.DarazTest"/>
</testsuite> <!-- TimedAssignment_AAndP_RegressionSuite -->
